/**
 * Material Symbols glyphs this app uses. The self-hosted icon font
 * (app/fonts/material-symbols.woff2) is a subset of exactly these names — the
 * full set is several megabytes. After adding a glyph here, run
 * `pnpm icons:pull` and commit the font, or it renders as its ligature text;
 * CI's `pnpm check:icons` fails until you do.
 */
export const ICON_NAMES = [
  'alternate_email',
  'arrow_back',
  'arrow_forward',
  'bolt',
  'chat',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'cloud_off',
  'edit',
  'error',
  'event',
  'event_available',
  'event_busy',
  'expand_less',
  'expand_more',
  'explore',
  'flag',
  'flight_takeoff',
  'groups',
  'home',
  'home_pin',
  'hourglass_top',
  'ios_share',
  'link',
  'location_on',
  'lock_clock',
  'logout',
  'mail',
  'menu',
  'my_location',
  'new_releases',
  'open_in_new',
  'person',
  'refresh',
  'route',
  'schedule',
  'school',
  'search',
  'settings',
  'share',
  'smart_display',
  'star',
  'translate',
  'upload_file',
  'verified_user',
  'videocam',
  'work',
  'workspace_premium',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
