/** Test and story data for the profile organisms. Not shipped in the app. */
import type { MentorProfile, ProfileSessionType, Review } from '@/types/mentor';

export const sessionTypes: ProfileSessionType[] = [
  {
    id: 'st1',
    name: 'SOP draft review',
    durationMin: 60,
    description:
      'We’ll work through your SOP draft together, focusing on how your story fits the program and your opening. You’ll leave with a prioritized revision list.',
    questions: [],
    category: 'Application documents',
    stage: 'Drafting',
    venue: 'Google Meet',
  },
  {
    id: 'st2',
    name: 'Mock visa interview',
    durationMin: 45,
    description: 'A realistic practice interview with honest notes on what to tighten.',
    questions: [],
    category: 'Visa and interview',
    stage: null,
    venue: 'Google Meet',
  },
  {
    id: 'st3',
    name: 'Program shortlist',
    durationMin: 30,
    description: 'Narrow your list to programs that fit your research and fund internationals.',
    questions: [],
    category: null,
    stage: 'Exploring',
    venue: 'EduFurther video',
  },
];

export const fullProfile: MentorProfile = {
  mentor: {
    id: 'm1',
    profileHref: '/mentors/gbenga',
    name: 'Gbenga Elufisan',
    firstName: 'Gbenga',
    initials: 'GE',
    photoUrl: null,
    photoFocus: null,
    tone: 2,
    degreeLine: 'PhD, Sociology',
    institution: 'Mississippi State University',
    completedSessions: 51,
    reviewCount: 7,
    rating: 4.9,
    label: 'top-rated',
    offer: 'free',
    nextAvailableAt: '2026-09-30T15:00:00Z',
    nextAvailableState: 'open',
    takingBookings: true,
    topics: [
      { slug: 'school-selection', label: 'School selection' },
      { slug: 'visa-and-interview', label: 'Visa and interview' },
      { slug: 'scholarships-funding', label: 'Scholarships & funding' },
    ],
  },
  takingBookings: true,
  names: { first: 'Gbenga', last: 'Elufisan' },
  headline: 'PhD Sociology · Mississippi State University',
  about:
    'A sociologist in training, focused on community development, agriculture and food systems, and inequality. I moved from Nigeria to a fully funded PhD at Mississippi State, and I’ve reviewed dozens of SOPs since. I’ll help you shortlist programs that fund, tell a clear story in your statement, and prepare for visa and admissions interviews. Past failures taught me as much as the wins, and I bring both to every session.',
  bannerUrl: null,
  cover: { color: null, art: 'none' },
  originCountry: 'Nigeria',
  studyCountry: 'United States',
  languages: ['English', 'Yoruba'],
  background: {
    originId: 'c-ng',
    studyId: 'c-us',
    languages: [
      { id: 'en', label: 'English' },
      { id: 'yo', label: 'Yoruba' },
    ],
  },
  socials: [
    { kind: 'linkedin', href: 'https://www.linkedin.com/in/gbenga' },
    { kind: 'youtube', href: 'https://www.youtube.com/@gbenga' },
  ],
  education: [
    { id: 'e1', title: 'PhD, Sociology', meta: 'Mississippi State University · 2023 – 2027' },
    { id: 'e2', title: 'MSc, Sociology', meta: 'Mississippi State University · 2021 – 2023' },
  ],
  awards: [
    {
      id: 'a1',
      title: 'Graduate Teaching Assistantship',
      meta: 'Mississippi State University · 2021',
    },
  ],
  sessionTypes: [sessionTypes[0]!],
  mentoringMinutes: 3060,
  menteesMentored: 27,
  attendanceRate: 88,
  // Mentor Profile.dc.html reviews tab.
  reviews: {
    count: 7,
    rating: 4.9,
    wouldRecommendIn10: 9,
    attributes: { communication: 86, knowledge: 96, support: 91, practicality: 91 },
  },
  owner: null,
};

/** No reviews, no sessions, nothing optional filled in. */
export const newProfile: MentorProfile = {
  ...fullProfile,
  mentor: {
    ...fullProfile.mentor,
    name: 'Oluwakemi Adebayo-Richardson Okonkwo',
    firstName: 'Oluwakemi',
    initials: 'OO',
    completedSessions: 0,
    reviewCount: 0,
    rating: null,
    label: 'new',
    nextAvailableState: 'none',
    nextAvailableAt: null,
    topics: [],
  },
  takingBookings: true,
  names: { first: 'Oluwadamilare', last: 'Adebayo-Ogunleye' },
  headline: null,
  about: null,
  originCountry: null,
  studyCountry: null,
  languages: [],
  background: { originId: null, studyId: null, languages: [] },
  socials: [],
  awards: [],
  mentoringMinutes: 0,
  menteesMentored: 0,
  attendanceRate: null,
  reviews: {
    count: 0,
    rating: null,
    wouldRecommendIn10: null,
    attributes: { communication: null, knowledge: null, support: null, practicality: null },
  },
};

/** Mentor Profile.dc.html `allReviews`, newest first. */
export const reviews: Review[] = [
  {
    id: 'r7',
    author: 'Pulane L.',
    initials: 'PL',
    institution: 'University of Cape Town',
    createdAt: '2026-04-19T12:00:00Z',
    rating: 4,
    topic: 'SOP draft review',
    text: 'Practical, direct feedback on my SOP draft. Would have loved a bit more time, but it was worth it.',
  },
  {
    id: 'r6',
    author: 'Taofeeq A.',
    initials: 'TA',
    institution: 'Obafemi Awolowo University',
    createdAt: '2026-03-02T12:00:00Z',
    rating: 5,
    topic: 'Program shortlist',
    text: 'Helped me cut a list of 14 programs to 6 that actually fit my research and fund internationals.',
  },
  {
    id: 'r5',
    author: 'Folake A.',
    initials: 'FA',
    institution: 'University of Lagos',
    createdAt: '2026-02-04T12:00:00Z',
    rating: 5,
    topic: 'SOP draft review',
    text: 'He related to my situation coming from a less common course of study and explained how to frame it as a strength.',
  },
  {
    id: 'r4',
    author: 'Deleted user',
    initials: '',
    institution: null,
    createdAt: '2025-11-16T12:00:00Z',
    rating: 5,
    topic: null,
    text: 'Glad I found this platform and my mentor. He showed me how to approach professors about assistantships.',
  },
  {
    id: 'r3',
    author: 'Muhammed O.',
    initials: 'MO',
    institution: 'Federal University Oye-Ekiti',
    createdAt: '2025-09-28T12:00:00Z',
    rating: 4,
    topic: 'Mock visa interview',
    text: 'Ran a mock visa interview with me and gave clear notes on what to tighten. Ready for the real one now.',
  },
];
